import { Image as ImageIcon, Grid } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

export function Gallery() {
  const emojis = [
    '2-people-fighting-for-donut.png',
    'astro-cat-surfing.png',
    'butterfly-in-a-car.png',
    'cat.png',
    'cat-and-dog.png',
    'dog-driving-a-car.png',
    'karate-cat.png',
    'pilot-on-space.png',
    'rocket-cat.png',
    'trex-cycling.png'
  ];

  return (
    <section id="gallery" className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
      <div className="text-center">
        <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-slate-300">
          <ImageIcon className="w-3.5 h-3.5" />
          Evidence of poor decision-making
        </span>
        <h3 className="mt-4 text-2xl sm:text-3xl font-semibold tracking-tight">Real emojis from people who should know better</h3>
        <p className="mt-3 text-sm text-slate-400">
          These are actual emojis generated by actual people. They paid money for this. You&apos;re considering doing the same. We&apos;re all complicit here.
        </p>
      </div>

      <div className="mt-10 grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-5 gap-3">
        {emojis.map((emoji, index) => (
          <div key={index} className="aspect-square rounded-xl border border-white/10 bg-white/5 p-2 hover:bg-white/[0.07] transition flex items-center justify-center overflow-hidden">
            <Image 
              src={`/gallery/${emoji}`}
              alt={`Emoji ${index + 1}`}
              width={200}
              height={200}
              className="w-full h-full object-contain"
            />
          </div>
        ))}
      </div>

      <div className="mt-8 text-center">
        <Link href="/sign-up" className="inline-flex items-center gap-2 rounded-md bg-white/10 hover:bg-white/15 ring-1 ring-white/15 text-sm px-4 py-2 transition">
          <Grid className="w-4 h-4" />
          Explore full gallery
        </Link>
      </div>
    </section>
  );
}

